spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pix
    username: postgres
    password: 12345678
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop  # ou o modo de sua escolha (validate, update, create, create-drop)
    properties:
      hibernate:
        format_sql: true
    application:
      name: gc